// examples/vue/templates/components/MoneyAmount.vue
<template>
  <span :class="[bold ? 'font-semibold' : '', cls].filter(Boolean).join(' ')" class="tabular-nums">
    {{ formatted }}
  </span>
</template>

<script setup lang="ts">
import { computed } from "vue";

const props = defineProps<{
  amount: number;
  bold?: boolean;
  cls?: string;
}>();

const formatted = computed(() => "$" + props.amount.toFixed(2));
</script>

// examples/react/templates/components/MoneyAmount.tsx
interface MoneyAmountProps {
  amount: number;
  bold?: boolean;
  className?: string;
}

export function MoneyAmount({ amount, bold, className }: MoneyAmountProps) {
  const formatted = "$" + amount.toFixed(2);
  const cls = [bold ? "font-semibold" : "", "tabular-nums", className]
    .filter(Boolean)
    .join(" ");
  return <span className={cls}>{formatted}</span>;
}
